# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v2/auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aegis/v2/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x65gis/v2/auth.proto\x12\x08\x61\x65gis.v2\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\'\n\x0fRefreshResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"&\n\rLogoutRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"!\n\x0eLogoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc4\x01\n\x0b\x41uthService\x12\x38\n\x05Login\x12\x16.aegis.v2.LoginRequest\x1a\x17.aegis.v2.LoginResponse\x12>\n\x07Refresh\x12\x18.aegis.v2.RefreshRequest\x1a\x19.aegis.v2.RefreshResponse\x12;\n\x06Logout\x12\x17.aegis.v2.LogoutRequest\x1a\x18.aegis.v2.LogoutResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v2.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v2'
  _globals['_LOGINREQUEST']._serialized_start=33
  _globals['_LOGINREQUEST']._serialized_end=80
  _globals['_LOGINRESPONSE']._serialized_start=82
  _globals['_LOGINRESPONSE']._serialized_end=142
  _globals['_REFRESHREQUEST']._serialized_start=144
  _globals['_REFRESHREQUEST']._serialized_end=183
  _globals['_REFRESHRESPONSE']._serialized_start=185
  _globals['_REFRESHRESPONSE']._serialized_end=224
  _globals['_LOGOUTREQUEST']._serialized_start=226
  _globals['_LOGOUTREQUEST']._serialized_end=264
  _globals['_LOGOUTRESPONSE']._serialized_start=266
  _globals['_LOGOUTRESPONSE']._serialized_end=299
  _globals['_AUTHSERVICE']._serialized_start=302
  _globals['_AUTHSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
