# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis.v2 import agent_pb2 as aegis_dot_v2_dot_agent__pb2


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/aegis.v2.AgentService/RegisterAgent',
                request_serializer=aegis_dot_v2_dot_agent__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_agent__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.UpdateAgentStatus = channel.unary_unary(
                '/aegis.v2.AgentService/UpdateAgentStatus',
                request_serializer=aegis_dot_v2_dot_agent__pb2.UpdateAgentStatusRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_agent__pb2.UpdateAgentStatusResponse.FromString,
                _registered_method=True)
        self.GetUploadLink = channel.unary_unary(
                '/aegis.v2.AgentService/GetUploadLink',
                request_serializer=aegis_dot_v2_dot_agent__pb2.GetUploadLinkRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_agent__pb2.GetUploadLinkResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterAgent(self, request, context):
        """RegisterAgent is the onboarding call for a new agent using a deployment token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAgentStatus(self, request, context):
        """UpdateAgentStatus updates the current state of a persistent agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUploadLink(self, request, context):
        """GetUploadLink returns a presigned URL for MinIO file uploads.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=aegis_dot_v2_dot_agent__pb2.RegisterAgentRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_agent__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'UpdateAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAgentStatus,
                    request_deserializer=aegis_dot_v2_dot_agent__pb2.UpdateAgentStatusRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_agent__pb2.UpdateAgentStatusResponse.SerializeToString,
            ),
            'GetUploadLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploadLink,
                    request_deserializer=aegis_dot_v2_dot_agent__pb2.GetUploadLinkRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_agent__pb2.GetUploadLinkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v2.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v2.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AgentService/RegisterAgent',
            aegis_dot_v2_dot_agent__pb2.RegisterAgentRequest.SerializeToString,
            aegis_dot_v2_dot_agent__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AgentService/UpdateAgentStatus',
            aegis_dot_v2_dot_agent__pb2.UpdateAgentStatusRequest.SerializeToString,
            aegis_dot_v2_dot_agent__pb2.UpdateAgentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUploadLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AgentService/GetUploadLink',
            aegis_dot_v2_dot_agent__pb2.GetUploadLinkRequest.SerializeToString,
            aegis_dot_v2_dot_agent__pb2.GetUploadLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
