# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v2/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aegis/v2/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x65gis/v2/agent.proto\x12\x08\x61\x65gis.v2\"3\n\x14RegisterAgentRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"?\n\x15RegisterAgentResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61gent_secret\x18\x02 \x01(\t\"<\n\x18UpdateAgentStatusRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\",\n\x19UpdateAgentStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"P\n\x14GetUploadLinkRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"4\n\x15GetUploadLinkResponse\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\"<\n\x18VerifyAgentSecretRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\t\"=\n\x19VerifyAgentSecretResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x11\n\ttenant_id\x18\x02 \x01(\t2\xee\x02\n\x0c\x41gentService\x12P\n\rRegisterAgent\x12\x1e.aegis.v2.RegisterAgentRequest\x1a\x1f.aegis.v2.RegisterAgentResponse\x12\\\n\x11UpdateAgentStatus\x12\".aegis.v2.UpdateAgentStatusRequest\x1a#.aegis.v2.UpdateAgentStatusResponse\x12P\n\rGetUploadLink\x12\x1e.aegis.v2.GetUploadLinkRequest\x1a\x1f.aegis.v2.GetUploadLinkResponse\x12\\\n\x11VerifyAgentSecret\x12\".aegis.v2.VerifyAgentSecretRequest\x1a#.aegis.v2.VerifyAgentSecretResponseBPZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v2.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2'
  _globals['_REGISTERAGENTREQUEST']._serialized_start=34
  _globals['_REGISTERAGENTREQUEST']._serialized_end=85
  _globals['_REGISTERAGENTRESPONSE']._serialized_start=87
  _globals['_REGISTERAGENTRESPONSE']._serialized_end=150
  _globals['_UPDATEAGENTSTATUSREQUEST']._serialized_start=152
  _globals['_UPDATEAGENTSTATUSREQUEST']._serialized_end=212
  _globals['_UPDATEAGENTSTATUSRESPONSE']._serialized_start=214
  _globals['_UPDATEAGENTSTATUSRESPONSE']._serialized_end=258
  _globals['_GETUPLOADLINKREQUEST']._serialized_start=260
  _globals['_GETUPLOADLINKREQUEST']._serialized_end=340
  _globals['_GETUPLOADLINKRESPONSE']._serialized_start=342
  _globals['_GETUPLOADLINKRESPONSE']._serialized_end=394
  _globals['_VERIFYAGENTSECRETREQUEST']._serialized_start=396
  _globals['_VERIFYAGENTSECRETREQUEST']._serialized_end=456
  _globals['_VERIFYAGENTSECRETRESPONSE']._serialized_start=458
  _globals['_VERIFYAGENTSECRETRESPONSE']._serialized_end=519
  _globals['_AGENTSERVICE']._serialized_start=522
  _globals['_AGENTSERVICE']._serialized_end=888
# @@protoc_insertion_point(module_scope)
