# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v2/agent.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x65gis/v2/agent.proto\x12\x08\x61\x65gis.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n\x14RegisterAgentRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"2\n\x15RegisterAgentResponse\x12\x19\n\x08\x61gent_id\x18\x01 \x01(\tR\x07\x61gentId\"M\n\x18UpdateAgentStatusRequest\x12\x19\n\x08\x61gent_id\x18\x01 \x01(\tR\x07\x61gentId\x12\x16\n\x06status\x18\x02 \x01(\tR\x06status\"5\n\x19UpdateAgentStatusResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"p\n\x14GetUploadLinkRequest\x12\x19\n\x08\x61gent_id\x18\x01 \x01(\tR\x07\x61gentId\x12\x1a\n\x08\x66ilename\x18\x02 \x01(\tR\x08\x66ilename\x12!\n\x0c\x63ontent_type\x18\x03 \x01(\tR\x0b\x63ontentType\"A\n\x15GetUploadLinkResponse\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n\x06method\x18\x02 \x01(\tR\x06method2\x90\x02\n\x0c\x41gentService\x12P\n\rRegisterAgent\x12\x1e.aegis.v2.RegisterAgentRequest\x1a\x1f.aegis.v2.RegisterAgentResponse\x12\\\n\x11UpdateAgentStatus\x12\".aegis.v2.UpdateAgentStatusRequest\x1a#.aegis.v2.UpdateAgentStatusResponse\x12P\n\rGetUploadLink\x12\x1e.aegis.v2.GetUploadLinkRequest\x1a\x1f.aegis.v2.GetUploadLinkResponseBJZHgithub.com/Aegis-AI-Organizations/Aegis-AI-Proto/gen/go/aegis/v2;aegisv2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v2.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZHgithub.com/Aegis-AI-Organizations/Aegis-AI-Proto/gen/go/aegis/v2;aegisv2'
  _globals['_REGISTERAGENTREQUEST']._serialized_start=67
  _globals['_REGISTERAGENTREQUEST']._serialized_end=131
  _globals['_REGISTERAGENTRESPONSE']._serialized_start=133
  _globals['_REGISTERAGENTRESPONSE']._serialized_end=183
  _globals['_UPDATEAGENTSTATUSREQUEST']._serialized_start=185
  _globals['_UPDATEAGENTSTATUSREQUEST']._serialized_end=262
  _globals['_UPDATEAGENTSTATUSRESPONSE']._serialized_start=264
  _globals['_UPDATEAGENTSTATUSRESPONSE']._serialized_end=317
  _globals['_GETUPLOADLINKREQUEST']._serialized_start=319
  _globals['_GETUPLOADLINKREQUEST']._serialized_end=431
  _globals['_GETUPLOADLINKRESPONSE']._serialized_start=433
  _globals['_GETUPLOADLINKRESPONSE']._serialized_end=498
  _globals['_AGENTSERVICE']._serialized_start=501
  _globals['_AGENTSERVICE']._serialized_end=773
# @@protoc_insertion_point(module_scope)
