# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis.v2 import auth_pb2 as aegis_dot_v2_dot_auth__pb2


class AuthServiceStub(object):
    """AuthService handles user authentication, session management, and JWT generation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/aegis.v2.AuthService/Login',
                request_serializer=aegis_dot_v2_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/aegis.v2.AuthService/Refresh',
                request_serializer=aegis_dot_v2_dot_auth__pb2.RefreshRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.RefreshResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/aegis.v2.AuthService/Logout',
                request_serializer=aegis_dot_v2_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetMe = channel.unary_unary(
                '/aegis.v2.AuthService/GetMe',
                request_serializer=aegis_dot_v2_dot_auth__pb2.GetMeRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.GetMeResponse.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/aegis.v2.AuthService/UpdateProfile',
                request_serializer=aegis_dot_v2_dot_auth__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.UpdateProfileResponse.FromString,
                _registered_method=True)
        self.UpdateEmail = channel.unary_unary(
                '/aegis.v2.AuthService/UpdateEmail',
                request_serializer=aegis_dot_v2_dot_auth__pb2.UpdateEmailRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.UpdateEmailResponse.FromString,
                _registered_method=True)
        self.UpdatePassword = channel.unary_unary(
                '/aegis.v2.AuthService/UpdatePassword',
                request_serializer=aegis_dot_v2_dot_auth__pb2.UpdatePasswordRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.UpdatePasswordResponse.FromString,
                _registered_method=True)
        self.RemoveAvatar = channel.unary_unary(
                '/aegis.v2.AuthService/RemoveAvatar',
                request_serializer=aegis_dot_v2_dot_auth__pb2.RemoveAvatarRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_auth__pb2.RemoveAvatarResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """AuthService handles user authentication, session management, and JWT generation.
    """

    def Login(self, request, context):
        """Login authenticates a user and returns an access token and refresh token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Refresh generates a new access token using a valid refresh token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout invalidates a refresh token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMe(self, request, context):
        """GetMe retrieves the authenticated user's profile and company information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """UpdateProfile updates the authenticated user's profile information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEmail(self, request, context):
        """UpdateEmail updates the authenticated user's email address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePassword(self, request, context):
        """UpdatePassword updates the authenticated user's password.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAvatar(self, request, context):
        """RemoveAvatar deletes the authenticated user's profile picture.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.RefreshRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.RefreshResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.LogoutResponse.SerializeToString,
            ),
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.GetMeRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.GetMeResponse.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.UpdateProfileRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.UpdateProfileResponse.SerializeToString,
            ),
            'UpdateEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEmail,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.UpdateEmailRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.UpdateEmailResponse.SerializeToString,
            ),
            'UpdatePassword': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePassword,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.UpdatePasswordRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.UpdatePasswordResponse.SerializeToString,
            ),
            'RemoveAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAvatar,
                    request_deserializer=aegis_dot_v2_dot_auth__pb2.RemoveAvatarRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_auth__pb2.RemoveAvatarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v2.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v2.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """AuthService handles user authentication, session management, and JWT generation.
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/Login',
            aegis_dot_v2_dot_auth__pb2.LoginRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/Refresh',
            aegis_dot_v2_dot_auth__pb2.RefreshRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/Logout',
            aegis_dot_v2_dot_auth__pb2.LogoutRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/GetMe',
            aegis_dot_v2_dot_auth__pb2.GetMeRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.GetMeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/UpdateProfile',
            aegis_dot_v2_dot_auth__pb2.UpdateProfileRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.UpdateProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/UpdateEmail',
            aegis_dot_v2_dot_auth__pb2.UpdateEmailRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.UpdateEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/UpdatePassword',
            aegis_dot_v2_dot_auth__pb2.UpdatePasswordRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.UpdatePasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.AuthService/RemoveAvatar',
            aegis_dot_v2_dot_auth__pb2.RemoveAvatarRequest.SerializeToString,
            aegis_dot_v2_dot_auth__pb2.RemoveAvatarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
