# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v2/auth.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x65gis/v2/auth.proto\x12\x08\x61\x65gis.v2\"@\n\x0cLoginRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"W\n\rLoginResponse\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\x12#\n\rrefresh_token\x18\x02 \x01(\tR\x0crefreshToken\"5\n\x0eRefreshRequest\x12#\n\rrefresh_token\x18\x01 \x01(\tR\x0crefreshToken\"4\n\x0fRefreshResponse\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\tR\x0b\x61\x63\x63\x65ssToken\"4\n\rLogoutRequest\x12#\n\rrefresh_token\x18\x01 \x01(\tR\x0crefreshToken\"*\n\x0eLogoutResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\"\x0e\n\x0cGetMeRequest\"\x9f\x01\n\rGetMeResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n\x05\x65mail\x18\x03 \x01(\tR\x05\x65mail\x12\x12\n\x04role\x18\x04 \x01(\tR\x04role\x12\x1d\n\ncompany_id\x18\x05 \x01(\tR\tcompanyId\x12!\n\x0c\x63ompany_name\x18\x06 \x01(\tR\x0b\x63ompanyName2\xfe\x01\n\x0b\x41uthService\x12\x38\n\x05Login\x12\x16.aegis.v2.LoginRequest\x1a\x17.aegis.v2.LoginResponse\x12>\n\x07Refresh\x12\x18.aegis.v2.RefreshRequest\x1a\x19.aegis.v2.RefreshResponse\x12;\n\x06Logout\x12\x17.aegis.v2.LogoutRequest\x1a\x18.aegis.v2.LogoutResponse\x12\x38\n\x05GetMe\x12\x16.aegis.v2.GetMeRequest\x1a\x17.aegis.v2.GetMeResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v2.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v2'
  _globals['_LOGINREQUEST']._serialized_start=33
  _globals['_LOGINREQUEST']._serialized_end=97
  _globals['_LOGINRESPONSE']._serialized_start=99
  _globals['_LOGINRESPONSE']._serialized_end=186
  _globals['_REFRESHREQUEST']._serialized_start=188
  _globals['_REFRESHREQUEST']._serialized_end=241
  _globals['_REFRESHRESPONSE']._serialized_start=243
  _globals['_REFRESHRESPONSE']._serialized_end=295
  _globals['_LOGOUTREQUEST']._serialized_start=297
  _globals['_LOGOUTREQUEST']._serialized_end=349
  _globals['_LOGOUTRESPONSE']._serialized_start=351
  _globals['_LOGOUTRESPONSE']._serialized_end=393
  _globals['_GETMEREQUEST']._serialized_start=395
  _globals['_GETMEREQUEST']._serialized_end=409
  _globals['_GETMERESPONSE']._serialized_start=412
  _globals['_GETMERESPONSE']._serialized_end=571
  _globals['_AUTHSERVICE']._serialized_start=574
  _globals['_AUTHSERVICE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
