# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis.v2 import billing_pb2 as aegis_dot_v2_dot_billing__pb2


class BillingServiceStub(object):
    """BillingService handles token management and consumption history.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/aegis.v2.BillingService/GetBalance',
                request_serializer=aegis_dot_v2_dot_billing__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_billing__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.GetLedger = channel.unary_unary(
                '/aegis.v2.BillingService/GetLedger',
                request_serializer=aegis_dot_v2_dot_billing__pb2.GetLedgerRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_billing__pb2.GetLedgerResponse.FromString,
                _registered_method=True)
        self.AdjustTokens = channel.unary_unary(
                '/aegis.v2.BillingService/AdjustTokens',
                request_serializer=aegis_dot_v2_dot_billing__pb2.AdjustTokensRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_billing__pb2.AdjustTokensResponse.FromString,
                _registered_method=True)
        self.PreFlightCheck = channel.unary_unary(
                '/aegis.v2.BillingService/PreFlightCheck',
                request_serializer=aegis_dot_v2_dot_billing__pb2.PreFlightCheckRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_billing__pb2.PreFlightCheckResponse.FromString,
                _registered_method=True)
        self.GetUsageStats = channel.unary_unary(
                '/aegis.v2.BillingService/GetUsageStats',
                request_serializer=aegis_dot_v2_dot_billing__pb2.GetUsageStatsRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_billing__pb2.GetUsageStatsResponse.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """BillingService handles token management and consumption history.
    """

    def GetBalance(self, request, context):
        """GetBalance retrieves the current token balance for a company.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLedger(self, request, context):
        """GetLedger retrieves the history of token transactions for a company.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustTokens(self, request, context):
        """AdjustTokens adds or subtracts tokens from a company's balance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreFlightCheck(self, request, context):
        """PreFlightCheck estimates the cost of a scan and checks if the balance is sufficient.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageStats(self, request, context):
        """GetUsageStats retrieves aggregated consumption data for graphs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=aegis_dot_v2_dot_billing__pb2.GetBalanceRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_billing__pb2.GetBalanceResponse.SerializeToString,
            ),
            'GetLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLedger,
                    request_deserializer=aegis_dot_v2_dot_billing__pb2.GetLedgerRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_billing__pb2.GetLedgerResponse.SerializeToString,
            ),
            'AdjustTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustTokens,
                    request_deserializer=aegis_dot_v2_dot_billing__pb2.AdjustTokensRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_billing__pb2.AdjustTokensResponse.SerializeToString,
            ),
            'PreFlightCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.PreFlightCheck,
                    request_deserializer=aegis_dot_v2_dot_billing__pb2.PreFlightCheckRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_billing__pb2.PreFlightCheckResponse.SerializeToString,
            ),
            'GetUsageStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageStats,
                    request_deserializer=aegis_dot_v2_dot_billing__pb2.GetUsageStatsRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_billing__pb2.GetUsageStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v2.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v2.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """BillingService handles token management and consumption history.
    """

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.BillingService/GetBalance',
            aegis_dot_v2_dot_billing__pb2.GetBalanceRequest.SerializeToString,
            aegis_dot_v2_dot_billing__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.BillingService/GetLedger',
            aegis_dot_v2_dot_billing__pb2.GetLedgerRequest.SerializeToString,
            aegis_dot_v2_dot_billing__pb2.GetLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.BillingService/AdjustTokens',
            aegis_dot_v2_dot_billing__pb2.AdjustTokensRequest.SerializeToString,
            aegis_dot_v2_dot_billing__pb2.AdjustTokensResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreFlightCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.BillingService/PreFlightCheck',
            aegis_dot_v2_dot_billing__pb2.PreFlightCheckRequest.SerializeToString,
            aegis_dot_v2_dot_billing__pb2.PreFlightCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.BillingService/GetUsageStats',
            aegis_dot_v2_dot_billing__pb2.GetUsageStatsRequest.SerializeToString,
            aegis_dot_v2_dot_billing__pb2.GetUsageStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
