# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aegis.v2 import company_pb2 as aegis_dot_v2_dot_company__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aegis/v2/company_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompanyServiceStub(object):
    """CompanyService handles registration and administrative management of companies.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCompany = channel.unary_unary(
                '/aegis.v2.CompanyService/CreateCompany',
                request_serializer=aegis_dot_v2_dot_company__pb2.CreateCompanyRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_company__pb2.CreateCompanyResponse.FromString,
                _registered_method=True)
        self.ListCompanies = channel.unary_unary(
                '/aegis.v2.CompanyService/ListCompanies',
                request_serializer=aegis_dot_v2_dot_company__pb2.ListCompaniesRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_company__pb2.ListCompaniesResponse.FromString,
                _registered_method=True)
        self.OnboardCompany = channel.unary_unary(
                '/aegis.v2.CompanyService/OnboardCompany',
                request_serializer=aegis_dot_v2_dot_company__pb2.OnboardCompanyRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_company__pb2.OnboardCompanyResponse.FromString,
                _registered_method=True)


class CompanyServiceServicer(object):
    """CompanyService handles registration and administrative management of companies.
    """

    def CreateCompany(self, request, context):
        """CreateCompany registers a new company in the system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCompanies(self, request, context):
        """ListCompanies retrieves all companies (SuperAdmin only).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OnboardCompany(self, request, context):
        """OnboardCompany handles the creation of a new company and its owner in one step.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCompany,
                    request_deserializer=aegis_dot_v2_dot_company__pb2.CreateCompanyRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_company__pb2.CreateCompanyResponse.SerializeToString,
            ),
            'ListCompanies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCompanies,
                    request_deserializer=aegis_dot_v2_dot_company__pb2.ListCompaniesRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_company__pb2.ListCompaniesResponse.SerializeToString,
            ),
            'OnboardCompany': grpc.unary_unary_rpc_method_handler(
                    servicer.OnboardCompany,
                    request_deserializer=aegis_dot_v2_dot_company__pb2.OnboardCompanyRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_company__pb2.OnboardCompanyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v2.CompanyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v2.CompanyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompanyService(object):
    """CompanyService handles registration and administrative management of companies.
    """

    @staticmethod
    def CreateCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.CompanyService/CreateCompany',
            aegis_dot_v2_dot_company__pb2.CreateCompanyRequest.SerializeToString,
            aegis_dot_v2_dot_company__pb2.CreateCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCompanies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.CompanyService/ListCompanies',
            aegis_dot_v2_dot_company__pb2.ListCompaniesRequest.SerializeToString,
            aegis_dot_v2_dot_company__pb2.ListCompaniesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OnboardCompany(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.CompanyService/OnboardCompany',
            aegis_dot_v2_dot_company__pb2.OnboardCompanyRequest.SerializeToString,
            aegis_dot_v2_dot_company__pb2.OnboardCompanyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
