# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v2/company.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61\x65gis/v2/company.proto\x12\x08\x61\x65gis.v2\"K\n\x14\x43reateCompanyRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n\x0bowner_email\x18\x02 \x01(\tR\nownerEmail\";\n\x15\x43reateCompanyResponse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\"\x16\n\x14ListCompaniesRequest\"O\n\x15ListCompaniesResponse\x12\x36\n\tcompanies\x18\x01 \x03(\x0b\x32\x18.aegis.v2.CompanySummaryR\tcompanies\"\x93\x01\n\x0e\x43ompanySummary\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n\x08owner_id\x18\x03 \x01(\tR\x07ownerId\x12\x1f\n\x0bowner_email\x18\x04 \x01(\tR\nownerEmail\x12!\n\x0cmember_count\x18\x05 \x01(\x05R\x0bmemberCount2\xb4\x01\n\x0e\x43ompanyService\x12P\n\rCreateCompany\x12\x1e.aegis.v2.CreateCompanyRequest\x1a\x1f.aegis.v2.CreateCompanyResponse\x12P\n\rListCompanies\x12\x1e.aegis.v2.ListCompaniesRequest\x1a\x1f.aegis.v2.ListCompaniesResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v2.company_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v2'
  _globals['_CREATECOMPANYREQUEST']._serialized_start=36
  _globals['_CREATECOMPANYREQUEST']._serialized_end=111
  _globals['_CREATECOMPANYRESPONSE']._serialized_start=113
  _globals['_CREATECOMPANYRESPONSE']._serialized_end=172
  _globals['_LISTCOMPANIESREQUEST']._serialized_start=174
  _globals['_LISTCOMPANIESREQUEST']._serialized_end=196
  _globals['_LISTCOMPANIESRESPONSE']._serialized_start=198
  _globals['_LISTCOMPANIESRESPONSE']._serialized_end=277
  _globals['_COMPANYSUMMARY']._serialized_start=280
  _globals['_COMPANYSUMMARY']._serialized_end=427
  _globals['_COMPANYSERVICE']._serialized_start=430
  _globals['_COMPANYSERVICE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
