# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v2/internal_auth.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61\x65gis/v2/internal_auth.proto\x12\x08\x61\x65gis.v2\"*\n\x12VerifyTokenRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\"H\n\x13VerifyTokenResponse\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid\x12\x1b\n\ttenant_id\x18\x02 \x01(\tR\x08tenantId2a\n\x13InternalAuthService\x12J\n\x0bVerifyToken\x12\x1c.aegis.v2.VerifyTokenRequest\x1a\x1d.aegis.v2.VerifyTokenResponseBPZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v2.internal_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2'
  _globals['_VERIFYTOKENREQUEST']._serialized_start=42
  _globals['_VERIFYTOKENREQUEST']._serialized_end=84
  _globals['_VERIFYTOKENRESPONSE']._serialized_start=86
  _globals['_VERIFYTOKENRESPONSE']._serialized_end=158
  _globals['_INTERNALAUTHSERVICE']._serialized_start=160
  _globals['_INTERNALAUTHSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
