# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis.v2 import internal_auth_pb2 as aegis_dot_v2_dot_internal__auth__pb2


class InternalAuthServiceStub(object):
    """InternalAuthService handles internal authentication and authorization between services.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerifyToken = channel.unary_unary(
                '/aegis.v2.InternalAuthService/VerifyToken',
                request_serializer=aegis_dot_v2_dot_internal__auth__pb2.VerifyTokenRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_internal__auth__pb2.VerifyTokenResponse.FromString,
                _registered_method=True)


class InternalAuthServiceServicer(object):
    """InternalAuthService handles internal authentication and authorization between services.
    """

    def VerifyToken(self, request, context):
        """VerifyToken validates a raw JWT token and returns the associated tenant information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalAuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=aegis_dot_v2_dot_internal__auth__pb2.VerifyTokenRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_internal__auth__pb2.VerifyTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v2.InternalAuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v2.InternalAuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalAuthService(object):
    """InternalAuthService handles internal authentication and authorization between services.
    """

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.InternalAuthService/VerifyToken',
            aegis_dot_v2_dot_internal__auth__pb2.VerifyTokenRequest.SerializeToString,
            aegis_dot_v2_dot_internal__auth__pb2.VerifyTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
