# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis.v2 import scan_pb2 as aegis_dot_v2_dot_scan__pb2


class ScanServiceStub(object):
    """ScanService handles orchestration of security scans.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScan = channel.unary_unary(
                '/aegis.v2.ScanService/StartScan',
                request_serializer=aegis_dot_v2_dot_scan__pb2.StartScanRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_scan__pb2.StartScanResponse.FromString,
                _registered_method=True)
        self.GetScanStatus = channel.unary_unary(
                '/aegis.v2.ScanService/GetScanStatus',
                request_serializer=aegis_dot_v2_dot_scan__pb2.GetScanStatusRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_scan__pb2.GetScanStatusResponse.FromString,
                _registered_method=True)
        self.ListScans = channel.unary_unary(
                '/aegis.v2.ScanService/ListScans',
                request_serializer=aegis_dot_v2_dot_scan__pb2.ListScansRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_scan__pb2.ListScansResponse.FromString,
                _registered_method=True)
        self.GetScanReport = channel.unary_unary(
                '/aegis.v2.ScanService/GetScanReport',
                request_serializer=aegis_dot_v2_dot_scan__pb2.GetScanReportRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_scan__pb2.GetScanReportResponse.FromString,
                _registered_method=True)
        self.WatchScanStatus = channel.unary_stream(
                '/aegis.v2.ScanService/WatchScanStatus',
                request_serializer=aegis_dot_v2_dot_scan__pb2.WatchScanStatusRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_scan__pb2.WatchScanStatusResponse.FromString,
                _registered_method=True)
        self.UpdateScanStatus = channel.unary_unary(
                '/aegis.v2.ScanService/UpdateScanStatus',
                request_serializer=aegis_dot_v2_dot_scan__pb2.UpdateScanStatusRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_scan__pb2.UpdateScanStatusResponse.FromString,
                _registered_method=True)


class ScanServiceServicer(object):
    """ScanService handles orchestration of security scans.
    """

    def StartScan(self, request, context):
        """StartScan initiates a new security scan for a target image.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanStatus(self, request, context):
        """GetScanStatus returns the current status and timing of a scan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScans(self, request, context):
        """ListScans retrieves a history of all scans.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanReport(self, request, context):
        """GetScanReport returns the PDF report data for a completed scan.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchScanStatus(self, request, context):
        """WatchScanStatus provides a stream of scan status updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScanStatus(self, request, context):
        """UpdateScanStatus updates the status of a scan (called by Agents).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=aegis_dot_v2_dot_scan__pb2.StartScanRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_scan__pb2.StartScanResponse.SerializeToString,
            ),
            'GetScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanStatus,
                    request_deserializer=aegis_dot_v2_dot_scan__pb2.GetScanStatusRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_scan__pb2.GetScanStatusResponse.SerializeToString,
            ),
            'ListScans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScans,
                    request_deserializer=aegis_dot_v2_dot_scan__pb2.ListScansRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_scan__pb2.ListScansResponse.SerializeToString,
            ),
            'GetScanReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanReport,
                    request_deserializer=aegis_dot_v2_dot_scan__pb2.GetScanReportRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_scan__pb2.GetScanReportResponse.SerializeToString,
            ),
            'WatchScanStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchScanStatus,
                    request_deserializer=aegis_dot_v2_dot_scan__pb2.WatchScanStatusRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_scan__pb2.WatchScanStatusResponse.SerializeToString,
            ),
            'UpdateScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScanStatus,
                    request_deserializer=aegis_dot_v2_dot_scan__pb2.UpdateScanStatusRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_scan__pb2.UpdateScanStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v2.ScanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v2.ScanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScanService(object):
    """ScanService handles orchestration of security scans.
    """

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.ScanService/StartScan',
            aegis_dot_v2_dot_scan__pb2.StartScanRequest.SerializeToString,
            aegis_dot_v2_dot_scan__pb2.StartScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.ScanService/GetScanStatus',
            aegis_dot_v2_dot_scan__pb2.GetScanStatusRequest.SerializeToString,
            aegis_dot_v2_dot_scan__pb2.GetScanStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.ScanService/ListScans',
            aegis_dot_v2_dot_scan__pb2.ListScansRequest.SerializeToString,
            aegis_dot_v2_dot_scan__pb2.ListScansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.ScanService/GetScanReport',
            aegis_dot_v2_dot_scan__pb2.GetScanReportRequest.SerializeToString,
            aegis_dot_v2_dot_scan__pb2.GetScanReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aegis.v2.ScanService/WatchScanStatus',
            aegis_dot_v2_dot_scan__pb2.WatchScanStatusRequest.SerializeToString,
            aegis_dot_v2_dot_scan__pb2.WatchScanStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.ScanService/UpdateScanStatus',
            aegis_dot_v2_dot_scan__pb2.UpdateScanStatusRequest.SerializeToString,
            aegis_dot_v2_dot_scan__pb2.UpdateScanStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
