# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v2/topology.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'aegis/v2/topology.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61\x65gis/v2/topology.proto\x12\x08\x61\x65gis.v2\"0\n\x0fNetworkTopology\x12\x1d\n\x05hosts\x18\x01 \x03(\x0b\x32\x0e.aegis.v2.Host\"\x89\x01\n\x04Host\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x14\n\x0cip_addresses\x18\x03 \x03(\t\x12\'\n\ncontainers\x18\x04 \x03(\x0b\x32\x13.aegis.v2.Container\x12$\n\tprocesses\x18\x05 \x03(\x0b\x32\x11.aegis.v2.Process\"\xcf\x01\n\tContainer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12$\n\tprocesses\x18\x04 \x03(\x0b\x32\x11.aegis.v2.Process\x12\x1d\n\x05ports\x18\x05 \x03(\x0b\x32\x0e.aegis.v2.Port\x12\x1a\n\rimage_version\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nimage_hash\x18\x07 \x01(\tH\x01\x88\x01\x01\x42\x10\n\x0e_image_versionB\r\n\x0b_image_hash\"l\n\x07Process\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x0c\x63ommand_line\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04user\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x0f\n\r_command_lineB\x07\n\x05_user\"F\n\x04Port\x12\x0e\n\x06number\x18\x01 \x01(\x05\x12\x10\n\x08protocol\x18\x02 \x01(\t\x12\x12\n\x05state\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_stateBPZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v2.topology_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZNgithub.com/Aegis-AI-Organizations/aegis-ai-api-gateway/internal/agrpc/aegis/v2'
  _globals['_NETWORKTOPOLOGY']._serialized_start=37
  _globals['_NETWORKTOPOLOGY']._serialized_end=85
  _globals['_HOST']._serialized_start=88
  _globals['_HOST']._serialized_end=225
  _globals['_CONTAINER']._serialized_start=228
  _globals['_CONTAINER']._serialized_end=435
  _globals['_PROCESS']._serialized_start=437
  _globals['_PROCESS']._serialized_end=545
  _globals['_PORT']._serialized_start=547
  _globals['_PORT']._serialized_end=617
# @@protoc_insertion_point(module_scope)
