# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis.v2 import topology_pb2 as aegis_dot_v2_dot_topology__pb2


class TopologyServiceStub(object):
    """TopologyService allows agents to export infrastructure data (hosts, containers, processes).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportTopology = channel.unary_unary(
                '/aegis.v2.TopologyService/ReportTopology',
                request_serializer=aegis_dot_v2_dot_topology__pb2.ReportTopologyRequest.SerializeToString,
                response_deserializer=aegis_dot_v2_dot_topology__pb2.ReportTopologyResponse.FromString,
                _registered_method=True)


class TopologyServiceServicer(object):
    """TopologyService allows agents to export infrastructure data (hosts, containers, processes).
    """

    def ReportTopology(self, request, context):
        """ReportTopology sends the discovered infrastructure state to the SaaS.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TopologyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTopology,
                    request_deserializer=aegis_dot_v2_dot_topology__pb2.ReportTopologyRequest.FromString,
                    response_serializer=aegis_dot_v2_dot_topology__pb2.ReportTopologyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v2.TopologyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v2.TopologyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TopologyService(object):
    """TopologyService allows agents to export infrastructure data (hosts, containers, processes).
    """

    @staticmethod
    def ReportTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v2.TopologyService/ReportTopology',
            aegis_dot_v2_dot_topology__pb2.ReportTopologyRequest.SerializeToString,
            aegis_dot_v2_dot_topology__pb2.ReportTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
