# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v1/ping.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x65gis/v1/ping.proto\x12\x08\x61\x65gis.v1\"\r\n\x0bPingRequest\"(\n\x0cPingResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2D\n\x0bPingService\x12\x35\n\x04Ping\x12\x15.aegis.v1.PingRequest\x1a\x16.aegis.v1.PingResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v1.ping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1'
  _globals['_PINGREQUEST']._serialized_start=33
  _globals['_PINGREQUEST']._serialized_end=46
  _globals['_PINGRESPONSE']._serialized_start=48
  _globals['_PINGRESPONSE']._serialized_end=88
  _globals['_PINGSERVICE']._serialized_start=90
  _globals['_PINGSERVICE']._serialized_end=158
# @@protoc_insertion_point(module_scope)
