# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v1/scan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "aegis/v1/scan.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13\x61\x65gis/v1/scan.proto\x12\x08\x61\x65gis.v1\x1a\x1fgoogle/protobuf/timestamp.proto"(\n\x10StartScanRequest\x12\x14\n\x0ctarget_image\x18\x01 \x01(\t"d\n\x11StartScanResponse\x12\x0f\n\x07scan_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12.\n\nstarted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"\'\n\x14GetScanStatusRequest\x12\x0f\n\x07scan_id\x18\x01 \x01(\t"\x9a\x01\n\x15GetScanStatusResponse\x12\x0f\n\x07scan_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12.\n\nstarted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x63ompleted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xa5\x01\n\x0bScanService\x12\x44\n\tStartScan\x12\x1a.aegis.v1.StartScanRequest\x1a\x1b.aegis.v1.StartScanResponse\x12P\n\rGetScanStatus\x12\x1e.aegis.v1.GetScanStatusRequest\x1a\x1f.aegis.v1.GetScanStatusResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "aegis.v1.scan_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = (
        b"Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1"
    )
    _globals["_STARTSCANREQUEST"]._serialized_start = 66
    _globals["_STARTSCANREQUEST"]._serialized_end = 106
    _globals["_STARTSCANRESPONSE"]._serialized_start = 108
    _globals["_STARTSCANRESPONSE"]._serialized_end = 208
    _globals["_GETSCANSTATUSREQUEST"]._serialized_start = 210
    _globals["_GETSCANSTATUSREQUEST"]._serialized_end = 249
    _globals["_GETSCANSTATUSRESPONSE"]._serialized_start = 252
    _globals["_GETSCANSTATUSRESPONSE"]._serialized_end = 406
    _globals["_SCANSERVICE"]._serialized_start = 409
    _globals["_SCANSERVICE"]._serialized_end = 574
# @@protoc_insertion_point(module_scope)
