# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis.v1 import scan_pb2 as aegis_dot_v1_dot_scan__pb2


class ScanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScan = channel.unary_unary(
                '/aegis.v1.ScanService/StartScan',
                request_serializer=aegis_dot_v1_dot_scan__pb2.StartScanRequest.SerializeToString,
                response_deserializer=aegis_dot_v1_dot_scan__pb2.StartScanResponse.FromString,
                _registered_method=True)
        self.GetScanStatus = channel.unary_unary(
                '/aegis.v1.ScanService/GetScanStatus',
                request_serializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.SerializeToString,
                response_deserializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.FromString,
                _registered_method=True)


class ScanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=aegis_dot_v1_dot_scan__pb2.StartScanRequest.FromString,
                    response_serializer=aegis_dot_v1_dot_scan__pb2.StartScanResponse.SerializeToString,
            ),
            'GetScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanStatus,
                    request_deserializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.FromString,
                    response_serializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v1.ScanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v1.ScanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v1.ScanService/StartScan',
            aegis_dot_v1_dot_scan__pb2.StartScanRequest.SerializeToString,
            aegis_dot_v1_dot_scan__pb2.StartScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v1.ScanService/GetScanStatus',
            aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.SerializeToString,
            aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
