# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis/v1/scan.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'aegis/v1/scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61\x65gis/v1/scan.proto\x12\x08\x61\x65gis.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n\x10StartScanRequest\x12!\n\x0ctarget_image\x18\x01 \x01(\tR\x0btargetImage\"\x7f\n\x11StartScanResponse\x12\x17\n\x07scan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n\x06status\x18\x02 \x01(\tR\x06status\x12\x39\n\nstarted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\"/\n\x14GetScanStatusRequest\x12\x17\n\x07scan_id\x18\x01 \x01(\tR\x06scanId\"\xc2\x01\n\x15GetScanStatusResponse\x12\x17\n\x07scan_id\x18\x01 \x01(\tR\x06scanId\x12\x16\n\x06status\x18\x02 \x01(\tR\x06status\x12\x39\n\nstarted_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n\x0c\x63ompleted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0b\x63ompletedAt2\xa5\x01\n\x0bScanService\x12\x44\n\tStartScan\x12\x1a.aegis.v1.StartScanRequest\x1a\x1b.aegis.v1.StartScanResponse\x12P\n\rGetScanStatus\x12\x1e.aegis.v1.GetScanStatusRequest\x1a\x1f.aegis.v1.GetScanStatusResponseB;Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis.v1.scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Aegis-AI-Organizations/aegis-ai-proto/aegis/v1'
  _globals['_STARTSCANREQUEST']._serialized_start=66
  _globals['_STARTSCANREQUEST']._serialized_end=119
  _globals['_STARTSCANRESPONSE']._serialized_start=121
  _globals['_STARTSCANRESPONSE']._serialized_end=248
  _globals['_GETSCANSTATUSREQUEST']._serialized_start=250
  _globals['_GETSCANSTATUSREQUEST']._serialized_end=297
  _globals['_GETSCANSTATUSRESPONSE']._serialized_start=300
  _globals['_GETSCANSTATUSRESPONSE']._serialized_end=494
  _globals['_SCANSERVICE']._serialized_start=497
  _globals['_SCANSERVICE']._serialized_end=662
# @@protoc_insertion_point(module_scope)
