# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
<<<<<<< HEAD
=======

>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)
import grpc

from aegis.v1 import scan_pb2 as aegis_dot_v1_dot_scan__pb2

<<<<<<< HEAD
=======
GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in aegis/v1/scan_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )

>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)

class ScanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartScan = channel.unary_unary(
<<<<<<< HEAD
                '/aegis.v1.ScanService/StartScan',
                request_serializer=aegis_dot_v1_dot_scan__pb2.StartScanRequest.SerializeToString,
                response_deserializer=aegis_dot_v1_dot_scan__pb2.StartScanResponse.FromString,
                _registered_method=True)
        self.GetScanStatus = channel.unary_unary(
                '/aegis.v1.ScanService/GetScanStatus',
                request_serializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.SerializeToString,
                response_deserializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.FromString,
                _registered_method=True)
=======
            "/aegis.v1.ScanService/StartScan",
            request_serializer=aegis_dot_v1_dot_scan__pb2.StartScanRequest.SerializeToString,
            response_deserializer=aegis_dot_v1_dot_scan__pb2.StartScanResponse.FromString,
            _registered_method=True,
        )
        self.GetScanStatus = channel.unary_unary(
            "/aegis.v1.ScanService/GetScanStatus",
            request_serializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.SerializeToString,
            response_deserializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.FromString,
            _registered_method=True,
        )
>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)


class ScanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
<<<<<<< HEAD
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
=======
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)

    def GetScanStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
<<<<<<< HEAD
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')
=======
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")
>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)


def add_ScanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
<<<<<<< HEAD
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=aegis_dot_v1_dot_scan__pb2.StartScanRequest.FromString,
                    response_serializer=aegis_dot_v1_dot_scan__pb2.StartScanResponse.SerializeToString,
            ),
            'GetScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanStatus,
                    request_deserializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.FromString,
                    response_serializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.v1.ScanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.v1.ScanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
=======
        "StartScan": grpc.unary_unary_rpc_method_handler(
            servicer.StartScan,
            request_deserializer=aegis_dot_v1_dot_scan__pb2.StartScanRequest.FromString,
            response_serializer=aegis_dot_v1_dot_scan__pb2.StartScanResponse.SerializeToString,
        ),
        "GetScanStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetScanStatus,
            request_deserializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.FromString,
            response_serializer=aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "aegis.v1.ScanService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("aegis.v1.ScanService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)
class ScanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
<<<<<<< HEAD
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v1.ScanService/StartScan',
=======
    def StartScan(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aegis.v1.ScanService/StartScan",
>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)
            aegis_dot_v1_dot_scan__pb2.StartScanRequest.SerializeToString,
            aegis_dot_v1_dot_scan__pb2.StartScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
<<<<<<< HEAD
            _registered_method=True)

    @staticmethod
    def GetScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.v1.ScanService/GetScanStatus',
=======
            _registered_method=True,
        )

    @staticmethod
    def GetScanStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/aegis.v1.ScanService/GetScanStatus",
>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)
            aegis_dot_v1_dot_scan__pb2.GetScanStatusRequest.SerializeToString,
            aegis_dot_v1_dot_scan__pb2.GetScanStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
<<<<<<< HEAD
            _registered_method=True)
=======
            _registered_method=True,
        )
>>>>>>> 3907786 ([UPDATE] gRPC server with verified implementation)
